# Generated by Django 4.2.4 on 2023-08-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0004_book_publisher_store_book_publisher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
