# Generated by Django 4.2.4 on 2023-08-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0005_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(to="my_app.author"),
        ),
    ]
